import logging
from typing import TypedDict, Annotated
from langgraph.graph import StateGraph, END
from services.embedding_service import model
from services.qdrant_service import client as qdrant_client
from config import QDRANT_COLLECTION

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

# Define the state for our LangGraph Agent
class AgentState(TypedDict):
    query: str
    context: str
    report: str

def retrieve_context(state: AgentState):
    """LangGraph Node: Queries the local Qdrant Vector DB via semantic search."""
    logger.info(f"Agent retrieving context for: {state['query']}")
    query_vector = model.encode(state['query']).tolist()
    
    search_result = qdrant_client.search(
        collection_name=QDRANT_COLLECTION,
        query_vector=query_vector,
        limit=5 
    )
    
    formatted_results = [hit.payload.get('text') for hit in search_result]
    return {"context": "\n\n---\n\n".join(formatted_results)}

def generate_report(state: AgentState):
    """
    LangGraph Node: In a full production setup, this node passes the context 
    to an LLM (like Claude or OpenAI) to generate a summary.
    For this headless implementation, we structure the final output.
    """
    logger.info("Agent generating report based on retrieved context.")
    # Here is where you would call llm.invoke() using langchain-anthropic
    # e.g., report = llm.invoke(f"Based on {state['context']}, answer {state['query']}")
    
    mock_llm_generation = f"AUTOGENERATED REPORT\nQuery: {state['query']}\n\nFindings based on Vector DB:\n{state['context']}"
    return {"report": mock_llm_generation}

# Build the LangGraph
workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("retrieve", retrieve_context)
workflow.add_node("generate", generate_report)

# Define the control flow
workflow.set_entry_point("retrieve")
workflow.add_edge("retrieve", "generate")
workflow.add_edge("generate", END)

# Compile the autonomous agent
autonomous_agent = workflow.compile()

if __name__ == "__main__":
    # Test the headless LangGraph agent
    print("Initializing Headless LangGraph Agent...")
    initial_state = {"query": "What are the key architectural decisions in Aegis?"}
    
    # Run the graph
    result = autonomous_agent.invoke(initial_state)
    print("\n--- FINAL AGENT OUTPUT ---")
    print(result["report"])